package sjc_folha_ui.gui;

import br.com.tiagoamp.sjcservice.model.input.InputSpreadsheet;
import br.com.tiagoamp.sjcservice.model.output.OutputSpreadsheet;
import br.com.tiagoamp.sjcservice.service.SjcServicesFacade;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author tiagoamp
 * 
 */
public class TelaInicial extends javax.swing.JFrame {

    private SjcServicesFacade service = new SjcServicesFacade();
    private final Path outputMsgFile = Paths.get("RESULTADO","MensagensProcesssamento.html");
    private Path outputXlsxFile = Paths.get("RESULTADO");
    
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        //this.setIconImage(new ImageIcon(getClass().getResource("/resources/logoIco.jpg")).getImage());
        
        // Dumb expiration procedure
        Path expFilePath = Paths.get("resources","exp.dat");
        
        try ( BufferedReader strR = new BufferedReader(new FileReader(expFilePath.toFile())) ) {
            String value = strR.readLine();
            if (!value.equals(getExpirationValue())) {
                JOptionPane.showMessageDialog(null, "Sistema expirado!","Erro", JOptionPane.ERROR_MESSAGE);  
                System.exit(1);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Arquivo de inicialização do sistema corrompido!","Erro", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }

    private String getExpirationValue() {
        // Dumbest expiration method ever...  :-P 
        //TODO: Implement a better one!
        Calendar calendar = Calendar.getInstance();
        Integer year = calendar.get(Calendar.YEAR);
        Integer result = year % 2 == 0 ? (year*3) : (year*4); 
        return String.valueOf(result);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tEntrada = new javax.swing.JTextField();
        tSaida = new javax.swing.JTextField();
        bAbrirEntrada = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bProcessar = new javax.swing.JButton();
        bValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SJC - Automatizador - by tiagoamp");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("SJC - Automatizador");

        bSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bSair.setText("SAIR");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Diretorio de entrada:");

        jLabel3.setText("Nome do Arquivo de saída (xlsx):");

        tEntrada.setEditable(false);

        tSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSaidaActionPerformed(evt);
            }
        });

        bAbrirEntrada.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        bAbrirEntrada.setText("Abrir");
        bAbrirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAbrirEntrada))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAbrirEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Ubuntu", 2, 10)); // NOI18N
        jLabel4.setText("Desenvolvido por @tiagoamp");

        bProcessar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bProcessar.setText("PROCESSAR");
        bProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProcessarActionPerformed(evt);
            }
        });

        bValidar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bValidar.setText("VALIDAR");
        bValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bSair, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSair)
                    .addComponent(bProcessar)
                    .addComponent(bValidar))
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSairActionPerformed

    private void bAbrirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirEntradaActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal != JFileChooser.APPROVE_OPTION) return;
        
        File arquivo = fileChooser.getSelectedFile();
        tEntrada.setText(arquivo.getPath());
        if (!arquivo.isDirectory()) {
            JOptionPane.showMessageDialog(null, "Arquivo inválido!","Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bAbrirEntradaActionPerformed

    private void bProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProcessarActionPerformed
        String in = tEntrada.getText();
        String out = tSaida.getText();
        
        if (!validateInputTexts(in, out)) return;
        
        Path dirPath = Paths.get(in);
        outputXlsxFile = outputXlsxFile.resolve(out);
        
        try {
            bProcessar.setEnabled(false);
            doAction("Processamento", dirPath);
            bProcessar.setEnabled(true);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Erro", JOptionPane.ERROR_MESSAGE);          
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);            
        }
        bProcessar.setEnabled(true);
    }//GEN-LAST:event_bProcessarActionPerformed

    private boolean validateInputTexts(String in, String out) {
        boolean validate = true;
        if (in.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Diretório com arquivos de entrada não selecionado!","Erro", JOptionPane.ERROR_MESSAGE);
            validate = false;
        }
        if (out.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome do arquivo de saída nao informado!","Erro", JOptionPane.ERROR_MESSAGE);
            validate = false;
        } else {
            if (!out.endsWith(".xlsx")) {
                JOptionPane.showMessageDialog(null, "Arquivo de saída deve ter extensão '.xlsx'!","Erro", JOptionPane.ERROR_MESSAGE);
                validate = false;
            }
        }        
        return validate;
    }
    
    private void doAction(String actionName, Path dirPath) throws IOException {
        List<InputSpreadsheet> listInputSpreadsheet = service.loadInputSpreadsheetsFromDirectory(dirPath);
        Object[] options = {"Continuar", "Cancelar"}; //Custom button text
        int response = JOptionPane.showOptionDialog(null, "["+actionName+"] Etapa 01 - Arquivos de entrada carregados!\nSelecione [Continuar] para prosseguir.",
                    "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    options, options[0]);
        if(response == JOptionPane.YES_OPTION){
            OutputSpreadsheet outSpreadsheet = service.generateOutputSpreadSheet(listInputSpreadsheet);
            service.generateOutputMessagesFile(outputMsgFile, outSpreadsheet);
            response = JOptionPane.showOptionDialog(null, "["+actionName+"] Etapa 02 - Dados de saída preparados!\nSelecione [Continuar] para prosseguir.",
                    "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    options, options[0]);
            if (response == JOptionPane.YES_OPTION) {
                if (actionName.equals("Validação")) {
                    JOptionPane.showMessageDialog(null, "Validação completa!\nAlertas e Erros gravados!\nResultado disponível no diretório: '/RESULTADOS'.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                service.generateOuputSpreadsheetFile(outputXlsxFile, outSpreadsheet);
                response = JOptionPane.showOptionDialog(null, "["+actionName+"] Etapa 03 - Planilha de Saída gerada!\nAlertas e Erros gravados!\nSelecione [Continuar] para prosseguir.",
                           "Confirmação", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                            options, options[0]);
                if (response == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(null, "Processamento concluído com sucesso!\nResultado disponível no diretório: '/RESULTADOS'.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                }                   
             }                
        }
    }
    
    private void bValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValidarActionPerformed
        String inputDir = tEntrada.getText();
        if (inputDir.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Diretório com arquivos de entrada não selecionado!","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Path dirPath = Paths.get(inputDir);
        
        try {
            bValidar.setEnabled(false);
            doAction("Validação", dirPath);
            bValidar.setEnabled(true);
        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Erro", JOptionPane.ERROR_MESSAGE);
        }        
        bValidar.setEnabled(true);
    }//GEN-LAST:event_bValidarActionPerformed

    private void tSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSaidaActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbrirEntrada;
    private javax.swing.JButton bProcessar;
    private javax.swing.JButton bSair;
    private javax.swing.JButton bValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tEntrada;
    private javax.swing.JTextField tSaida;
    // End of variables declaration//GEN-END:variables
}
